export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";


export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";


export const IDEAS_LOADING = "IDEAS_LOADING";
export const IDEAS_LOAD_SUCCESS = "IDEAS_LOAD_SUCCESS";
export const IDEAS_LOAD_ERROR = "IDEAS_LOAD_ERROR";

export const DELETE_IDEA_LOADING = "DELETE_IDEA_LOADING";
export const DELETE_IDEA_SUCCESS = "DELETE_IDEA_SUCCESS";
export const DELETE_IDEA_ERROR = "DELETE_IDEA_ERROR";

export const UPDATE_IDEA_LOADING = "DELETE_IDEA_ERROR";
export const UPDATE_IDEA_SUCCESS = "UPDATE_IDEA_SUCCESS";
export const UPDATE_IDEA_ERROR = "UPDATE_IDEA_ERROR";

export const ADD_IDEA_LOADING = "ADD_IDEA_LOADING";
export const ADD_IDEA_SUCCESS = "ADD_IDEA_SUCCESS";
export const ADD_IDEA_ERROR = "ADD_IDEA_ERROR";